### ISSUE TITLE
Referensi Tugas Akhir SA

### ISSUE THREAD

**Issue by bibiehadi** [bibiehadi/TA-StrategiAlgoritma#1]
Selamat Sore Pak Go, untuk tugas akhir SA ini kami mengambil permasalahan kurang lebih seperti di makalah dibawah ini. Apakah masih bisa dilanjutkan atau harus ganti permasalahan? 
@goFrendiAsgard 
[MakalahStima-2016-098.pdf](https://github.com/bibiehadi/TA-StrategiAlgoritma/files/2169815/MakalahStima-2016-098.pdf)

**Comment by goFrendiAsgard** [comment]
Bisa. tapi seperti yang sudah ditunjukkan di jurnal, kita tidak bisa hanya sekedar mengubah graph menjadi tree. Setiap kali melakukan pemberian warna, semua tetangga yang sudah diwarnai juga harus dilihat.
